In [39]:
import pandas as pd
import os

directory = '../../../../Data/School/0001'
file_name_label = '0001_otsu label.txt'

file_label = os.path.join(directory, file_name_label)

In [40]:
import googletrans
from googletrans import Translator
translator = Translator()

In [41]:
file_name_data = '0001_otsu.dat'

file_data = os.path.join(directory, file_name_data)
df = pd.read_csv(file_data, sep = '\t', error_bad_lines = False)

In [42]:
with open(file_label, 'r') as f:
    x = f.read().splitlines()

In [43]:
def get_list_of_lists(x):
    # Return each row as a list
    list_of_lists = []
    for line in x:
        list_of_lists.append(line.split('\t'))
    return list_of_lists

In [44]:
list_of_lists = get_list_of_lists(x)

In [45]:
def search_index(keyword, list_of_lists = list_of_lists):
    # Check if the keyword is in the list
    idx_list = []
    for idx, item in enumerate(list_of_lists):
        if keyword in item[0]:
            idx_list.append(idx)
    return idx_list

In [46]:
# Split list_of_lists to variable info list and varuable value list

In [47]:
hensu_joho_idx = search_index('変数情報')[0] # id of 変数情報

In [48]:
hensu_chi_idx = search_index('変数値')[0] # id of 変数値

In [49]:
# split the list of lists
list_of_lists_info = list_of_lists[hensu_joho_idx:hensu_chi_idx] # Contains value informaiotn
list_of_lists_val = list_of_lists[hensu_chi_idx:-1] # Contains value variables

In [50]:
list_of_lists_val_1st_elem = [item[0] for item in list_of_lists_val] # First elements in val list

In [51]:
_list_of_vars_val  = [s for s in list_of_lists_val_1st_elem if s] # list of variables in the values list

In [52]:
list_of_vars_val = _list_of_vars_val[2:]

In [53]:
def return_next_var(var, list_of_vars):
    # Use list of variables, taken from var_info, return the next variable
    current_idx = list_of_vars.index(var)
    next_var = list_of_vars[current_idx + 1]
    return next_var

In [54]:
def get_dict(var, 
             list_of_lists = list_of_lists_val,
             list_of_lists_1st_elem = list_of_lists_val_1st_elem, 
             list_of_vars = list_of_vars_val):
    # Return dictionary for var
    
    dict = {}    
    idx = list_of_lists_1st_elem.index(var)    
    
    if var != list_of_vars[-1]:
        # Get the next variable using the list of variables in the values list
        next_var = return_next_var(var, list_of_vars)
    
        # Get the index for the list of lists of values        
        next_idx = list_of_lists_1st_elem.index(next_var)
        sublist = list_of_lists[idx:next_idx]
        
    else:
        sublist = list_of_lists[idx:]
    # Slice the list of lists
        
    for item in sublist:
        new_dict = {item[1]:item[2]}
        dict.update(new_dict)
    return dict

In [55]:
def replace_val(var, df = df):
    dictionary = get_dict(var)
    df[var] = df[var].astype(str)
    df[var] = df[var].map(dictionary)

In [56]:
def trans_dict(dictionary):
    # Translate dictionary
    dict_eng = {}
    for key, values in dictionary.items():
        dict_eng[key] = translator.translate(values).text.replace(' ', '_')
    
    return dict_eng

In [57]:
def replace_val_trans(var, df = df):
    dictionary = get_dict(var)
    dict_eng = trans_dict(dictionary)
    df[var] = df[var].astype(str)
    df[var] = df[var].map(dict_eng)

In [58]:
for var in list_of_vars_val:
    replace_val(var)
#    replace_val_trans(var)

In [59]:
# Can be used to replace column names
variables_list = [(item[0], item[2]) for item in list_of_lists_info[3:-1]]

In [60]:
variables_dict = dict(variables_list)

In [61]:
get_dict('q6')

{'1': '農業',
 '2': '林業',
 '3': '漁業',
 '4': '工業',
 '5': '建設業',
 '6': '製造業',
 '7': '商業',
 '8': '飲食店',
 '9': '金融・保険',
 '10': '不動産',
 '11': '陸運業',
 '12': '海運業',
 '13': 'その他の運輸',
 '14': '通信',
 '15': 'ガス・電気・水道',
 '16': '修理',
 '17': 'サービス',
 '18': '興業・娯楽',
 '19': '医学・教育・宗教',
 '20': '食料品',
 '21': '煙草',
 '22': '紡織',
 '23': '衣販',
 '24': '木材',
 '25': '家具',
 '26': '紙',
 '27': '印刷',
 '28': '化学',
 '29': '石油',
 '30': 'ゴム',
 '31': '皮革',
 '32': 'ガラス・土石',
 '33': '一金',
 '34': '金属',
 '35': '機械',
 '36': '電機',
 '37': '運機',
 '38': '精機',
 '39': '製造業その他',
 '40': '製造業不明',
 '41': '公務',
 '42': 'その他',
 '43': '不明',
 '99': '無回答'}

In [62]:
get_dict('q7')

{'1': '川崎市',
 '9': '横浜市',
 '10': '横浜市鶴見区',
 '11': '横浜市港北区',
 '12': '横浜市保土ヶ谷区',
 '13': '横浜市神奈川区',
 '14': '横浜市西区',
 '15': '横浜市中区',
 '16': '横浜市南区',
 '17': '横浜市磯子区',
 '18': '横浜市金沢区',
 '19': '横浜市戸塚区',
 '20': '鎌倉市',
 '30': '逗子・葉山',
 '40': '横須賀市',
 '41': '横須賀市横須賀・浦賀',
 '42': '横須賀市大楠・武山・北下浦',
 '50': '三浦郡南部',
 '60': '藤沢市',
 '70': '茅ヶ崎市',
 '80': '平塚市',
 '90': '高座郡',
 '91': '高座郡相模原町',
 '92': '高座郡座間町',
 '93': '高座郡その他',
 '101': '中郡大磯町・国府町・二宮町・大野町・旭村・土沢村',
 '102': '中郡その他',
 '110': '愛甲郡',
 '120': '津久井郡',
 '130': '足柄上郡',
 '140': '小田原市・足柄下郡',
 '150': '東京都',
 '160': 'その他の県',
 '999': '無回答'}

In [63]:
variables_dict

{'seibetu': '性別',
 'q2_1': '選択科目・1',
 'q2_2': '選択科目・2',
 'q2_3': '選択科目・3',
 'q2_4': '選択科目・4',
 'q2_5': '選択科目・5',
 'q2_6': '選択科目・6',
 'q3.1': '跡取りか',
 'q3.2': '保護者との続柄',
 'q4.1': '保護者の職業',
 'q4.3.1': '家の生活程度',
 'q4.3.2': '家族数',
 'q6': '就職先の事業内容',
 'q7': '就職先の所在地',
 'q8': '就職先の規模',
 'q9.1.2': '本人の仕事の内容',
 'q9.2': '養成工か見習いか',
 'q10': '初任給',
 'q11': '他出か通勤か',
 'q12': '就職経路',
 'q13': '進学'}

In [64]:
df['q12']

0           知人
1        学校と職安
2        学校と職安
3        学校と職安
4        学校と職安
         ...
13098       職安
13099       職安
13100       職安
13101       会社
13102       家族
Name: q12, Length: 13103, dtype: object

In [65]:
#df.rename(columns = variables_dict, inplace=True)

In [66]:
import matplotlib.pyplot as plt
%matplotlib inline

In [67]:
df['q4.1']

0        単純労務者
1           無職
2           工員
3           無職
4           無職
         ...
13098       農業
13099       農業
13100       農業
13101       農業
13102       農業
Name: q4.1, Length: 13103, dtype: object

In [75]:
df

,gakkou,seibetu,q2_1,q2_2,q2_3,q2_4,q2_5,q2_6,q3.1,q3.2,...,q4.3.2,q6,q7,q8,q9.1.2,q9.2,q10,q11,q12,q13
0,101,男子,工,NaN,NaN,NaN,NaN,NaN,跡取り,三男・三女,...,NaN,一金,川崎市,NaN,鍛冶工,養成工,NaN,通勤,知人,NaN
1,101,男子,工,NaN,NaN,NaN,NaN,NaN,跡取り,次男・次女,...,NaN,電機,横浜市鶴見区,NaN,鋳物工,養成工,NaN,通勤,学校と職安,NaN
2,101,男子,英,NaN,NaN,NaN,NaN,NaN,跡取り,長男・長女,...,NaN,電機,川崎市,NaN,電機器組立工,養成工,NaN,通勤,学校と職安,NaN
3,101,男子,商,NaN,NaN,NaN,NaN,NaN,跡取りでない,次男・次女,...,NaN,電機,川崎市,NaN,工作機械工,養成工,NaN,通勤,学校と職安,NaN
4,101,男子,英,NaN,NaN,NaN,NaN,NaN,跡取りでない,三男・三女,...,NaN,電機,川崎市,NaN,工作機械工,養成工,NaN,通勤,学校と職安,進学している
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13098,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,三男・三女,...,NaN,紡織,高座郡その他,NaN,その他の紡織関係職業,無回答,NaN,他出,職安,NaN
13099,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,次男・次女,...,NaN,紡織,高座郡その他,NaN,編立工,無回答,NaN,他出,職安,NaN
13100,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,長男・長女,...,NaN,紡織,高座郡その他,NaN,編立工,無回答,NaN,他出,職安,NaN
13101,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,次男・次女,...,NaN,紡織,東京都,NaN,織布工,無回答,NaN,他出,会社,NaN
13102,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,長男・長女,...,NaN,商業,その他の県,NaN,衣類仕立職,見習い,NaN,他出,家族,NaN

In [76]:
# Can be used to replace column names
variables_list = [(item[0], item[2]) for item in list_of_lists_info[3:-1]]

In [77]:
variables_dict = dict(variables_list)

In [78]:
variables_dict

{'seibetu': '性別',
 'q2_1': '選択科目・1',
 'q2_2': '選択科目・2',
 'q2_3': '選択科目・3',
 'q2_4': '選択科目・4',
 'q2_5': '選択科目・5',
 'q2_6': '選択科目・6',
 'q3.1': '跡取りか',
 'q3.2': '保護者との続柄',
 'q4.1': '保護者の職業',
 'q4.3.1': '家の生活程度',
 'q4.3.2': '家族数',
 'q6': '就職先の事業内容',
 'q7': '就職先の所在地',
 'q8': '就職先の規模',
 'q9.1.2': '本人の仕事の内容',
 'q9.2': '養成工か見習いか',
 'q10': '初任給',
 'q11': '他出か通勤か',
 'q12': '就職経路',
 'q13': '進学'}

In [79]:
df.rename(columns = variables_dict, inplace=True)

In [82]:
df

,gakkou,性別,選択科目・1,選択科目・2,選択科目・3,選択科目・4,選択科目・5,選択科目・6,跡取りか,保護者との続柄,...,家族数,就職先の事業内容,就職先の所在地,就職先の規模,本人の仕事の内容,養成工か見習いか,初任給,他出か通勤か,就職経路,進学
0,101,男子,工,NaN,NaN,NaN,NaN,NaN,跡取り,三男・三女,...,NaN,一金,川崎市,NaN,鍛冶工,養成工,NaN,通勤,知人,NaN
1,101,男子,工,NaN,NaN,NaN,NaN,NaN,跡取り,次男・次女,...,NaN,電機,横浜市鶴見区,NaN,鋳物工,養成工,NaN,通勤,学校と職安,NaN
2,101,男子,英,NaN,NaN,NaN,NaN,NaN,跡取り,長男・長女,...,NaN,電機,川崎市,NaN,電機器組立工,養成工,NaN,通勤,学校と職安,NaN
3,101,男子,商,NaN,NaN,NaN,NaN,NaN,跡取りでない,次男・次女,...,NaN,電機,川崎市,NaN,工作機械工,養成工,NaN,通勤,学校と職安,NaN
4,101,男子,英,NaN,NaN,NaN,NaN,NaN,跡取りでない,三男・三女,...,NaN,電機,川崎市,NaN,工作機械工,養成工,NaN,通勤,学校と職安,進学している
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13098,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,三男・三女,...,NaN,紡織,高座郡その他,NaN,その他の紡織関係職業,無回答,NaN,他出,職安,NaN
13099,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,次男・次女,...,NaN,紡織,高座郡その他,NaN,編立工,無回答,NaN,他出,職安,NaN
13100,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,長男・長女,...,NaN,紡織,高座郡その他,NaN,編立工,無回答,NaN,他出,職安,NaN
13101,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,次男・次女,...,NaN,紡織,東京都,NaN,織布工,無回答,NaN,他出,会社,NaN
13102,1312,女子,英,家,NaN,NaN,NaN,NaN,跡取りでない,長男・長女,...,NaN,商業,その他の県,NaN,衣類仕立職,見習い,NaN,他出,家族,NaN

In [84]:
df[df['就職先の所在地']=='川崎市']

,gakkou,性別,選択科目・1,選択科目・2,選択科目・3,選択科目・4,選択科目・5,選択科目・6,跡取りか,保護者との続柄,...,家族数,就職先の事業内容,就職先の所在地,就職先の規模,本人の仕事の内容,養成工か見習いか,初任給,他出か通勤か,就職経路,進学
0,101,男子,工,NaN,NaN,NaN,NaN,NaN,跡取り,三男・三女,...,NaN,一金,川崎市,NaN,鍛冶工,養成工,NaN,通勤,知人,NaN
2,101,男子,英,NaN,NaN,NaN,NaN,NaN,跡取り,長男・長女,...,NaN,電機,川崎市,NaN,電機器組立工,養成工,NaN,通勤,学校と職安,NaN
3,101,男子,商,NaN,NaN,NaN,NaN,NaN,跡取りでない,次男・次女,...,NaN,電機,川崎市,NaN,工作機械工,養成工,NaN,通勤,学校と職安,NaN
4,101,男子,英,NaN,NaN,NaN,NaN,NaN,跡取りでない,三男・三女,...,NaN,電機,川崎市,NaN,工作機械工,養成工,NaN,通勤,学校と職安,進学している
5,101,男子,商,NaN,NaN,NaN,NaN,NaN,跡取り,長男・長女,...,NaN,金属,川崎市,NaN,自動車組立工,養成工,NaN,通勤,学校と職安,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12829,1302,男子,農,NaN,NaN,NaN,NaN,NaN,跡取り,長男・長女,...,無回答,電機,川崎市,NaN,溶接工・溶断工,無回答,無回答,他出,学校,NaN
12876,1303,女子,家,NaN,NaN,NaN,NaN,NaN,跡取りでない,無回答,...,NaN,紡織,川崎市,NaN,その他の紡織関係職業,無回答,NaN,他出,無回答,NaN
12913,1304,女子,家,NaN,NaN,NaN,NaN,NaN,跡取りでない,三男・三女,...,NaN,紡織,川崎市,NaN,毛織・紡績,無回答,NaN,他出,職安,NaN
12914,1304,女子,家,NaN,NaN,NaN,NaN,NaN,跡取りでない,長男・長女,...,NaN,紡織,川崎市,NaN,毛織・紡績,無回答,NaN,他出,職安,NaN
13078,1311,女子,家,NaN,NaN,NaN,NaN,NaN,跡取りでない,四男・四女以上,...,NaN,紡織,川崎市,NaN,毛織・紡績,無回答,NaN,他出,職安,NaN

In [ ]:
df_dummies = pd.get_dummies(df, columns = [''])

In [100]:
df_grouped = df.groupby('就職先の所在地').count()

In [102]:
df_grouped.get_group(1)

AttributeError: 'DataFrame' object has no attribute 'get_group'

In [96]:
df.columns

Index(['gakkou', '性別', '選択科目・1', '選択科目・2', '選択科目・3', '選択科目・4', '選択科目・5',
       '選択科目・6', '跡取りか', '保護者との続柄', '保護者の職業', '家の生活程度', '家族数', '就職先の事業内容',
       '就職先の所在地', '就職先の規模', '本人の仕事の内容', '養成工か見習いか', '初任給', '他出か通勤か', '就職経路',
       '進学'],
      dtype='object')